"""Module contains configuration values."""

WIDTH = 40
HEIGHT = 20
OBSTACLE_RATE = 0
RELATIVE_OBSTACLE_N = 0
STEP = 100
CELL_SIZE = 10
SCHEME = (10, 8, 5, 3)
POPULATION_SIZE = 10
GAMES_PER_GENERATION = 10
MAX_TURNS = 100
SURVIVING_ODDS = 0.5
MUTATION_CHANCE = 0.1
MAX_WORKING_THREADS = 1
