"""Module contains configuration values."""

WIDTH = 40
HEIGHT = 20
OBSTACLE_RATE = 0
RELATIVE_OBSTACLE_N = 0.01
STEP = 100
CELL_SIZE = 10
SCHEME = (3, 2, 1)
ACTIVATION = 'relu_leaky'
MAX_SCAN_DISTANCE = 10
POPULATION_SIZE = 100
GAMES_PER_GENERATION = 20
MAX_TURNS = 100
SURVIVING_ODDS = 0.4
MUTATION_CHANCE = 0.1
MUTATION_POWER = 0.1
